# Build tuning-workbench-synth with JUCE buidls

trigger:
- main

pr:
- main

jobs:

- job: Build
  strategy:
    matrix:
      mac:
        imageName: 'macos-10.14'
        isMac: True
        doUpload: True
      win-2017:
        imageName: 'vs2017-win2016'
        isWindows: True
      win-2019:
        imageName: 'windows-2019'
        isWindows: True
        doUpload: True
      lin-18:
        imageName: 'ubuntu-18.04'
        isLinux: True
        doUpload: True
      lin-20:
        imageName: 'ubuntu-20.04'
        isLinux: True

  pool:
    vmImage: $(imageName)

  steps:
  - checkout: self
    fetchDepth: 1
    # submodules: recursive # can't do submodules here b'cuz depth=1 fails with Github


  - bash: |
      sudo apt-get update
      sudo apt-get install -y libgtk-3-dev
      sudo apt-get install -y libwebkit2gtk-4.0
      sudo apt-get install -y libwebkit2gtk-4.0-dev
      sudo apt-get install -y libcurl4-openssl-dev
      sudo apt-get install -y alsa
      sudp apt-get install -y alsa-tools
      sudo apt-get install -y libasound2-dev
      sudo apt-get install -y jack
      sudo apt-get install -y libjack-dev
      sudo apt-get install -y libfreetype6-dev
      sudo apt-get install -y libxinerama-dev
      sudo apt-get install -y libxcb-xinerama0
      sudo apt-get install -y libxinerama1
      sudo apt-get install -y x11proto-xinerama-dev
      sudo apt-get install -y libxrandr-dev
      sudo apt-get install -y libgl1-mesa-dev
      sudo apt-get install -y libxcursor-dev 
      sudo apt-get install -y libxcursor1 
      sudo apt-get install -y libxcb-cursor-dev 
      sudo apt-get install -y libxcb-cursor0
      sudo apt-get install -y --fix-missing

      apt list --installed

      find /usr/include -name "asoundlib.h" -print
    displayName: Prepare Linux Host
    condition: variables.isLinux

  - bash: |
      git submodule update --init --recursive
    displayName: Submodule Update

  - bash: |
      export SVER=`cat VERSION`
      export GH=`git log -1 --format=%h`
      echo "Version ${SVER} hash ${GH}"
      # make it available below
      echo "##vso[task.setvariable variable=STOCHAS_VERSION]${SVER}"
      echo "##vso[task.setvariable variable=GH]${GH}"
    displayName: Determine Version

  #
  #  MAC
  #
  - bash: |
      set -ex
      # For now we expand this out so we can swap the STOCHAS_IS_SYNTH flag for the AU off
      cmake -Bbuild -GXcode -DSTOCHAS_VERSION=${STOCHAS_VERSION} 
      cmake --build build --target stochas_VST3 --config Release | xcpretty
      cmake --build build --target stochas_Standalone --config Release | xcpretty

      mkdir build/tmpasset
      mv build/stochas_artefacts/Release/VST3 build/tmpasset
      mv build/stochas_artefacts/Release/Standalone build/tmpasset

      cmake -Bbuild -DSTOCHAS_IS_SYNTH=FALSE -DSTOCHAS_VERSION=${STOCHAS_VERSION} 
      cmake --build build --target stochas_AU --config Release | xcpretty
      cp -r build/stochas_artefacts/Release/AU/* build/tmpasset
      
      NM=stochas-${STOCHAS_VERSION}.${GH}-mac.dmg

      mkdir -p build/product/
      hdiutil create build/product/${NM} -ov -volname "Stochas ${STOCHAS_VERSION}" -fs HFS+ -srcfolder build/tmpasset

    displayName: Build Mac
    condition: variables.isMac
  
  #
  # MAC INSTALLER
  #
  - bash: |
      # pull the packages from build assets to save bandwidth since this is normally a bit slow from the 
      # original site
      wget -O mac_packages https://github.com/surge-synthesizer/build-assets/raw/master/packages/Packages.dmg
      mv mac_packages $(brew --cache -s packages)
      brew cask install packages
      mkdir -p build/stochaspkg
      packagesbuild  --build-folder build/stochaspkg --package-version ${STOCHAS_VERSION} "install/mac/Stochas.pkgproj"
      NM=stochas-${STOCHAS_VERSION}.${GH}-mac-installer.dmg
      hdiutil create -volname "Stochas ${STOCHAS_VERSION} Installer" -srcfolder build/stochaspkg -ov -format UDRO build/product/${NM}
    displayName: Build Mac Installer
    condition: and(variables.isMac, variables.doUpload)

  #
  # WIN
  #
  - bash: |
      set -ex
      # 64 bit
      cmake -Bbuild -A x64 -DSTOCHAS_VERSION=${STOCHAS_VERSION} -DWIN_ARCH=x64
      cmake --build build --config Release --target installer-pkg 
      # 32 bit      
      cmake -Bbuild32 -A Win32 -DSTOCHAS_VERSION=${STOCHAS_VERSION} -DWIN_ARCH=x86
      cmake --build build32 --config Release --target installer-pkg
    displayName: Build Windows
    condition: variables.isWindows
  #
  # WIN SETUP
  #
  - bash: |
      set -ex
      # build the innosetup install
      nuget install innosetup
      mkdir -p build/product/
      iscc //Obuild\\product //Fstochas_setup.${STOCHAS_VERSION}.${GH} //DSTOCHAS_VERSION=${STOCHAS_VERSION}.${GH} "install\\win\\install.iss"

    displayName: Package Windows
    condition: and(variables.isWindows, variables.doUpload)

  #
  # LINUX
  #   
  - bash: |
      set -ex
      cmake -Bbuild -DSTOCHAS_VERSION=${STOCHAS_VERSION}
      cmake --build build --config Release --target installer-pkg 
    displayName: Build Linux
    condition: variables.isLinux

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'MACOS_BUILD'
      targetPath: 'build/product/'
    displayName: Publish Mac DMG
    condition: and(variables.isMac, variables.doUpload)

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'WINDOWS_BUILD'
      targetPath: 'build/product/'
    displayName: Publish Windows Zip
    condition: and(variables.isWindows, variables.doUpload)

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'LINUX_BUILD'
      targetPath: 'build/product/'
    displayName: Publish Linux Tar
    condition: and(variables.isLinux, variables.doUpload)


- job: UpdateGithubRelease
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

  steps:
  - task: DownloadPipelineArtifact@0
    inputs:
      artifactName: 'MACOS_BUILD'
      targetPath: $(Build.ArtifactStagingDirectory)

  - task: DownloadPipelineArtifact@0
    inputs:
      artifactName: 'WINDOWS_BUILD'
      targetPath: $(Build.ArtifactStagingDirectory)

  - task: DownloadPipelineArtifact@0
    inputs:
      artifactName: 'LINUX_BUILD'
      targetPath: $(Build.ArtifactStagingDirectory)

  - bash: |
     scripts/release-notes.sh > $(Build.ArtifactStagingDirectory)/ReleaseNotes.md
     ls $(Build.ArtifactStagingDirectory)
     md5sum $(Build.ArtifactStagingDirectory)/*

    displayName: Fake up release notes and tag release

  - task: GitHubRelease@0
    displayName: "Create New Github Release"
    inputs:
      gitHubConnection: surge-rackupdater
      repositoryName: surge-synthesizer/stochas
      action: 'edit'
      tag: Nightly
      target: '$(Build.SourceVersion)'
      addChangeLog: false
      assetUploadMode: 'delete'
      releaseNotesFile: $(Build.ArtifactStagingDirectory)/ReleaseNotes.md
      assets: $(Build.ArtifactStagingDirectory)/*.*
